apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  namespace: default
spec:
  serviceName: nginx-sts
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            port: 80
            path: /
 
