apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-2
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: canary
      version: "2.0"
  template:
    metadata:
      labels:
        app: canary
        version: "2.0"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            port: 80
            path: /
 
