apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-1
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: canary
      version: "1.0"
  template:
    metadata:
      labels:
        app: canary
        version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            port: 80
            path: /
 
